# -*- coding: utf-8 -*-
"""Challenge_Motiva.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AEOjfVzRynNruE89ET4ad9iw6P-4ldVY
"""

# %matplotlib inline
from __future__ import annotations

import argparse
import sys
import warnings
from dataclasses import dataclass
from datetime import datetime, timedelta

import numpy as np
import pandas as pd
import requests

NASA_POWER_URL = "https://power.larc.nasa.gov/api/temporal/daily/point"
SOILGRIDS_URL = "https://rest.isric.org/soilgrids/v2.0/properties/query"

INCERTEZA_PADRAO_PCT = 0.30
FAIXA_VALIDADE = {
    "temperatura_c": (0.0, 45.0),
    "par_mol_m2_dia": (0.0, 60.0),
    "etr_etm_ou_theta_theta_cr": (0.0, 1.0),
}

COLUNAS_CLIMA_OBRIGATORIAS = ["data", "tmax_c", "tmin_c", "precip_mm", "radiacao_mj_m2"]

@dataclass
class EspecieParams:

    nome_cientifico: str
    nome_popular: str
    habito_aplicacao: str

    tb: float       # temperatura base
    topt: float     # temperatura ótima
    tmax: float     # temperatura-teto

    ta_max_cm_dia: float   # taxa de crescimento máxima (cm/dia)
    h_max_cm: float        # altura máxima típica em condições ideais (cm)

    # -- curva logística de altura por GDD --
    gdd_25: float           # GDD acumulado p/ 25% de Hmax (°C·dia)
    gdd_50: float           # GDD acumulado p/ 50% de Hmax (°C·dia)
    gdd_75: float           # GDD acumulado p/ 75% de Hmax (°C·dia)
    k_logistico: float      # inclinação da logística (valor positivo; usado como -k)

    # -- resposta à radiação --
    alpha_par: float          # coef. em f(PAR) = 1 - exp(-alpha * iPAR)
    k_extincao: float = 0.55  # Beer-Lambert, iPAR = PAR*(1-exp(-k*LAI)); 0.5-0.6 típico
    lai_max: float = 2.5

    # -- resposta hídrica:
    tipo_estresse_hidrico: str = "etr_etm"   # "etr_etm" ou "exponencial"
    expoente_hidrico: float = 1.0            # usado se tipo == "etr_etm": f(W)=(ETr/ETm)^exp
    gamma_hidrico: float = 3.5               # usado se tipo == "exponencial": f(W)=1-exp(-gamma*theta/theta_cr)
    sensibilidade_hidrica_pct_mm: float = 1.0  # % de redução na TA por mm de déficit acumulado (referência/documental)


    # estimativa por hábito de crescimento/porte a partir da literatura geral
    # de turfgrass (faixa típica 0.55-0.80); recalibrar localmente se possível.
    kc_turf: float = 0.65

    # referência bibliográfica/documental usada na calibração (ajuste se tiver a fonte exata)
    referencia: str = (
        "Parâmetros de literatura geral (ver documento de embasamento fornecido) "
        "-- sem calibração de campo local."
    )


ESPECIES: dict[str, EspecieParams] = {
    "santo_agostinho": EspecieParams(
        nome_cientifico="Stenotaphrum secundatum", nome_popular="Santo Agostinho",
        habito_aplicacao="Estolonífero/rizomatoso -- rebrote pós-corte (corte mín. 3 cm)",
        tb=10.0, topt=31.0, tmax=40.0,
        ta_max_cm_dia=0.45, h_max_cm=15.0,
        gdd_25=180.0, gdd_50=340.0, gdd_75=550.0, k_logistico=0.012,
        alpha_par=0.08, tipo_estresse_hidrico="etr_etm", expoente_hidrico=1.0,
        sensibilidade_hidrica_pct_mm=1.2, kc_turf=0.70,
    ),
    "bermuda": EspecieParams(
        nome_cientifico="Cynodon dactylon", nome_popular="Bermuda",
        habito_aplicacao="Estolonífero/rizomatoso -- rebrote pós-corte, crescimento muito rápido",
        tb=12.0, topt=35.0, tmax=42.0,
        ta_max_cm_dia=1.20, h_max_cm=25.0,
        gdd_25=120.0, gdd_50=230.0, gdd_75=380.0, k_logistico=0.018,
        alpha_par=0.05, tipo_estresse_hidrico="exponencial", gamma_hidrico=3.5,
        sensibilidade_hidrica_pct_mm=1.8, kc_turf=0.70,
    ),
    "centipede": EspecieParams(
        nome_cientifico="Eremochloa ophiuroides", nome_popular="Centipede",
        habito_aplicacao="Estolonífero de crescimento lento -- crescimento primário e rebrote",
        tb=11.0, topt=29.0, tmax=38.0,
        ta_max_cm_dia=0.20, h_max_cm=10.0,
        gdd_25=210.0, gdd_50=420.0, gdd_75=680.0, k_logistico=0.009,
        alpha_par=0.09, tipo_estresse_hidrico="etr_etm", expoente_hidrico=1.0,
        sensibilidade_hidrica_pct_mm=0.9, kc_turf=0.60,
    ),
    "bahia": EspecieParams(
        nome_cientifico="Paspalum notatum", nome_popular="Bahia",
        habito_aplicacao="Cespitoso/rizomatoso agressivo -- rebrote pós-corte e crescimento com hastes florais",
        tb=13.0, topt=33.0, tmax=40.0,
        ta_max_cm_dia=0.85, h_max_cm=35.0,  # 18.0 cm no hábito vegetativo (sem hastes florais)
        gdd_25=150.0, gdd_50=290.0, gdd_75=460.0, k_logistico=0.014,
        alpha_par=0.06, tipo_estresse_hidrico="etr_etm", expoente_hidrico=0.65,
        sensibilidade_hidrica_pct_mm=0.7, kc_turf=0.65,
    ),
    "sao_carlos": EspecieParams(
        nome_cientifico="Axonopus compressus", nome_popular="São Carlos",
        habito_aplicacao="Estolonífero, tolerante a sombra/umidade -- rebrote pós-poda",
        tb=10.0, topt=28.0, tmax=36.0,
        ta_max_cm_dia=0.50, h_max_cm=18.0,
        gdd_25=160.0, gdd_50=310.0, gdd_75=520.0, k_logistico=0.011,
        alpha_par=0.12, tipo_estresse_hidrico="etr_etm", expoente_hidrico=1.4,
        sensibilidade_hidrica_pct_mm=2.1, kc_turf=0.65,
    ),
    "esmeralda": EspecieParams(
        nome_cientifico="Zoysia japonica", nome_popular="Esmeralda",
        habito_aplicacao="Rizomatosa/estolonífera, crescimento moderado -- rebrote pós-corte",
        tb=8.5, topt=30.0, tmax=38.0,
        ta_max_cm_dia=0.30, h_max_cm=12.0,
        gdd_25=220.0, gdd_50=450.0, gdd_75=720.0, k_logistico=0.008,
        alpha_par=0.07, tipo_estresse_hidrico="etr_etm", expoente_hidrico=1.0,
        sensibilidade_hidrica_pct_mm=1.1, kc_turf=0.65,
    ),
    "coreana": EspecieParams(
        nome_cientifico="Zoysia tenuifolia (Z. pacifica)", nome_popular="Coreana",
        habito_aplicacao="Densíssima, filiforme, crescimento vertical baixíssimo -- crescimento primário contínuo",
        tb=9.0, topt=29.0, tmax=37.0,
        ta_max_cm_dia=0.08, h_max_cm=6.0,
        gdd_25=350.0, gdd_50=700.0, gdd_75=1150.0, k_logistico=0.005,
        alpha_par=0.10, tipo_estresse_hidrico="etr_etm", expoente_hidrico=0.8,
        sensibilidade_hidrica_pct_mm=0.8, kc_turf=0.55,
    ),
    "kikuyo": EspecieParams(
        nome_cientifico="Pennisetum clandestinum", nome_popular="Kikuyo",
        habito_aplicacao="Estolonífera/rizomatosa agressiva, clima subtropical de altitude -- rebrote rápido pós-corte",
        tb=8.0, topt=25.0, tmax=35.0,
        ta_max_cm_dia=1.40, h_max_cm=30.0,
        gdd_25=100.0, gdd_50=200.0, gdd_75=340.0, k_logistico=0.020,
        alpha_par=0.04, tipo_estresse_hidrico="etr_etm", expoente_hidrico=1.0,
        sensibilidade_hidrica_pct_mm=1.6, kc_turf=0.75,
    ),
    "seashore_paspalum": EspecieParams(
        nome_cientifico="Paspalum vaginatum", nome_popular="Seashore Paspalum",
        habito_aplicacao="Estolonífera/rizomatosa, alta tolerância à salinidade -- rebrote pós-corte",
        tb=11.5, topt=32.0, tmax=40.0,
        ta_max_cm_dia=0.60, h_max_cm=15.0,
        gdd_25=140.0, gdd_50=280.0, gdd_75=480.0, k_logistico=0.013,
        alpha_par=0.06, tipo_estresse_hidrico="etr_etm", expoente_hidrico=1.0,
        sensibilidade_hidrica_pct_mm=1.0, kc_turf=0.65,
    ),
    "buffalo_grass": EspecieParams(
        nome_cientifico="Bouteloua dactyloides", nome_popular="Buffalo grass",
        habito_aplicacao="Dioica, estolonífera, clima semiárido/temperado-quente -- crescimento primário e rebrote, alta resiliência hídrica",
        tb=7.0, topt=28.0, tmax=37.0,
        ta_max_cm_dia=0.35, h_max_cm=12.0,
        gdd_25=170.0, gdd_50=330.0, gdd_75=540.0, k_logistico=0.010,
        alpha_par=0.08, tipo_estresse_hidrico="etr_etm", expoente_hidrico=0.5,
        sensibilidade_hidrica_pct_mm=0.6, kc_turf=0.55,
    ),
}

def buscar_clima(lat: float, lon: float, data_ini: str, data_fim: str) -> pd.DataFrame:
    """Retorna DataFrame diário com T2M_MAX, T2M_MIN, PRECTOTCORR, RH2M, ALLSKY_SFC_SW_DWN."""
    params = {
        "parameters": "T2M_MAX,T2M_MIN,T2M,PRECTOTCORR,RH2M,ALLSKY_SFC_SW_DWN",
        "community": "AG",
        "longitude": lon,
        "latitude": lat,
        "start": data_ini.replace("-", ""),
        "end": data_fim.replace("-", ""),
        "format": "JSON",
    }
    resp = requests.get(NASA_POWER_URL, params=params, timeout=60)
    resp.raise_for_status()
    payload = resp.json()["properties"]["parameter"]

    df = pd.DataFrame(payload)
    df.index = pd.to_datetime(df.index, format="%Y%m%d")
    df = df.sort_index()
    df = df.rename(columns={
        "T2M_MAX": "tmax_c",
        "T2M_MIN": "tmin_c",
        "T2M": "tmed_c",
        "PRECTOTCORR": "precip_mm",
        "RH2M": "umid_rel_pct",
        "ALLSKY_SFC_SW_DWN": "radiacao_mj_m2",
    })
    # NASA POWER usa -999 como flag de dado ausente
    df = df.replace(-999.0, np.nan).interpolate(limit_direction="both")
    return df


def buscar_solo(lat: float, lon: float) -> dict:
    params = {
        "lon": lon,
        "lat": lat,
        "property": ["clay", "sand", "silt", "soc"],
        "depth": "0-30cm",
        "value": "mean",
    }
    try:
        resp = requests.get(SOILGRIDS_URL, params=params, timeout=60)
        resp.raise_for_status()
        layers = resp.json()["properties"]["layers"]
        valores = {}
        for layer in layers:
            nome = layer["name"]
            v = layer["depths"][0]["values"]["mean"]
            fator = 10.0 if nome != "soc" else 100.0
            valores[nome] = v / fator if v is not None else np.nan
        return {
            "argila_pct": valores.get("clay", 25.0),
            "areia_pct": valores.get("sand", 45.0),
            "silte_pct": valores.get("silt", 30.0),
            "carbono_organico_pct": valores.get("soc", 1.5),
            "fonte": "SoilGrids v2.0 (ISRIC)",
        }
    except requests.RequestException as exc:
        print(f"[aviso] SoilGrids indisponível ({exc}); usando textura padrão de fallback.",
              file=sys.stderr)
        return {
            "argila_pct": 25.0,
            "areia_pct": 45.0,
            "silte_pct": 30.0,
            "carbono_organico_pct": 1.5,
            "fonte": "fallback (franco-argilo-arenoso, sem confirmação local)",
        }

def capacidade_agua_disponivel(argila_pct: float, areia_pct: float) -> float:
    clay = argila_pct / 100.0
    sand = areia_pct / 100.0

    cc = (-0.251 * sand + 0.195 * clay + 0.011 * 1.0
          + 0.006 * (sand * 1.0) - 0.027 * (clay * 1.0)
          + 0.452 * (sand * clay) + 0.299)
    pmp = (-0.024 * sand + 0.487 * clay + 0.006 * 1.0
           + 0.005 * (sand * 1.0) - 0.013 * (clay * 1.0)
           + 0.068 * (sand * clay) + 0.031)

    cc = max(cc, pmp + 0.02)
    return (cc - pmp) * 10.0  # mm de água disponível por cm de solo


def et0_hargreaves(tmax: pd.Series, tmin: pd.Series, tmed: pd.Series,
                    radiacao_mj_m2: pd.Series) -> pd.Series:
    return 0.0023 * (tmed + 17.8) * np.sqrt(np.maximum(tmax - tmin, 0)) * (radiacao_mj_m2 * 0.408)


def converter_par_mol(radiacao_mj_m2: pd.Series | float) -> pd.Series | float:
    return radiacao_mj_m2 * 0.45 * 4.6


def calcular_disponibilidade_hidrica(df_clima: pd.DataFrame, esp: EspecieParams,
                                      agua_disp_mm_cm: float,
                                      profundidade_raiz_cm: float = 15.0) -> pd.DataFrame:
    df = df_clima.copy()
    df["eto_mm"] = et0_hargreaves(df["tmax_c"], df["tmin_c"], df["tmed_c"], df["radiacao_mj_m2"])

    capacidade_total_mm = agua_disp_mm_cm * profundidade_raiz_cm
    reservatorio = capacidade_total_mm
    reservatorios, fatores = [], []
    for precip, eto in zip(df["precip_mm"], df["eto_mm"]):
        reservatorio = reservatorio + precip - eto
        reservatorio = min(max(reservatorio, 0.0), capacidade_total_mm)
        fator = reservatorio / capacidade_total_mm if capacidade_total_mm > 0 else 1.0
        reservatorios.append(reservatorio)
        fatores.append(fator)

    df["reservatorio_mm"] = reservatorios
    df["fator_agua_solo"] = fatores  # 0-1, proporção bruta reservatório/capacidade

    if esp.tipo_estresse_hidrico == "etr_etm":
        df["etr_etm"] = np.clip(np.array(fatores) * 1.2, 0.15, 1.0)
    else:
        df["theta_theta_cr"] = np.clip(np.array(fatores), 0.0, 1.0)

    return df

def graus_dia_diario(tmax_c: float, tmin_c: float, tb: float) -> float:
    return max(0.0, (tmax_c + tmin_c) / 2.0 - tb)

def modelo_gdd(gdd_acumulado: float, esp: EspecieParams) -> float:
    if gdd_acumulado < 0:
        warnings.warn(f"GDD acumulado negativo ({gdd_acumulado:.1f}); truncando para 0.")
        gdd_acumulado = 0.0
    return esp.h_max_cm / (1 + np.exp(-esp.k_logistico * (gdd_acumulado - esp.gdd_50)))

def modelo_beta(t_med_c: float, esp: EspecieParams) -> float:
    if t_med_c <= esp.tb or t_med_c >= esp.tmax:
        warnings.warn(
            f"{esp.nome_popular}: temperatura média {t_med_c:.1f}°C fora da faixa "
            f"cardeal calibrada [{esp.tb}, {esp.tmax}]°C -- fator térmico = 0 "
            "(confira se a unidade de entrada está correta)."
        )
        return 0.0
    expoente = (esp.tmax - esp.topt) / (esp.topt - esp.tb)
    termo1 = (t_med_c - esp.tb) / (esp.topt - esp.tb)
    termo2 = ((esp.tmax - t_med_c) / (esp.tmax - esp.topt)) ** expoente
    return float(np.clip(termo1 * termo2, 0.0, 1.0))

def modelo_par(par_incidente_mol_m2_dia: float, esp: EspecieParams,
               lai_atual: float | None = None) -> float:
    if par_incidente_mol_m2_dia < FAIXA_VALIDADE["par_mol_m2_dia"][0]:
        warnings.warn(f"PAR negativo ({par_incidente_mol_m2_dia}); truncando para 0.")
        par_incidente_mol_m2_dia = 0.0
    elif par_incidente_mol_m2_dia > FAIXA_VALIDADE["par_mol_m2_dia"][1]:
        warnings.warn(
            f"PAR incidente {par_incidente_mol_m2_dia:.1f} mol·m⁻²·dia⁻¹ acima da "
            f"faixa de validade esperada ({FAIXA_VALIDADE['par_mol_m2_dia'][1]}); "
            "confira a unidade (mol·m⁻²·dia⁻¹, não MJ·m⁻²·dia⁻¹)."
        )
    lai = lai_atual if lai_atual is not None else esp.lai_max
    lai = max(0.0, lai)
    ipar = par_incidente_mol_m2_dia * (1 - np.exp(-esp.k_extincao * lai))
    return float(1 - np.exp(-esp.alpha_par * ipar))

def modelo_hidrico(esp: EspecieParams, etr_etm: float | None = None,
                    theta_sobre_theta_cr: float | None = None) -> float:
    lo, hi = FAIXA_VALIDADE["etr_etm_ou_theta_theta_cr"]
    if esp.tipo_estresse_hidrico == "etr_etm":
        if etr_etm is None:
            raise ValueError(
                f"{esp.nome_popular} usa o modelo hídrico 'etr_etm': informe etr_etm (razão ETr/ETm)."
            )
        etr_etm_clip = float(np.clip(etr_etm, lo, hi))
        if etr_etm_clip != etr_etm:
            warnings.warn(f"{esp.nome_popular}: etr_etm={etr_etm:.2f} fora de [{lo},{hi}]; truncado para {etr_etm_clip:.2f}.")
        return etr_etm_clip ** esp.expoente_hidrico
    elif esp.tipo_estresse_hidrico == "exponencial":
        if theta_sobre_theta_cr is None:
            raise ValueError(
                f"{esp.nome_popular} usa o modelo hídrico 'exponencial': informe theta_sobre_theta_cr."
            )
        theta_clip = float(np.clip(theta_sobre_theta_cr, lo, hi * 3))
        if theta_clip != theta_sobre_theta_cr:
            warnings.warn(f"{esp.nome_popular}: theta/theta_cr={theta_sobre_theta_cr:.2f} truncado para {theta_clip:.2f}.")
        return float(1 - np.exp(-esp.gamma_hidrico * theta_clip))
    else:
        raise ValueError(f"tipo_estresse_hidrico desconhecido: {esp.tipo_estresse_hidrico!r}")

def modelo_rue(t_med_c: float, par_incidente_mol_m2_dia: float, esp: EspecieParams,
               etr_etm: float | None = None, theta_sobre_theta_cr: float | None = None,
               lai_atual: float | None = None) -> float:
    f_t = modelo_beta(t_med_c, esp)
    f_par = modelo_par(par_incidente_mol_m2_dia, esp, lai_atual=lai_atual)
    f_w = modelo_hidrico(esp, etr_etm=etr_etm, theta_sobre_theta_cr=theta_sobre_theta_cr)
    return esp.ta_max_cm_dia * f_t * f_par * f_w

def pesos_por_rmse_inverso(rmse_gdd: float, rmse_rue: float) -> tuple[float, float]:
    inv_gdd = 1.0 / max(rmse_gdd, 1e-6)
    inv_rue = 1.0 / max(rmse_rue, 1e-6)
    total = inv_gdd + inv_rue
    return inv_gdd / total, inv_rue / total

def modelo_hibrido(gdd_acumulado_hoje: float, gdd_acumulado_ontem: float,
                    t_med_c: float, par_incidente_mol_m2_dia: float,
                    esp: EspecieParams,
                    etr_etm: float | None = None, theta_sobre_theta_cr: float | None = None,
                    lai_atual: float | None = None,
                    peso_gdd: float = 0.4, peso_rue: float = 0.6) -> float:
    if not np.isclose(peso_gdd + peso_rue, 1.0):
        raise ValueError(f"peso_gdd ({peso_gdd}) + peso_rue ({peso_rue}) deve somar 1.0")

    h_hoje = modelo_gdd(gdd_acumulado_hoje, esp)
    h_ontem = modelo_gdd(gdd_acumulado_ontem, esp)
    ta_gdd = max(0.0, h_hoje - h_ontem)

    ta_rue = modelo_rue(t_med_c, par_incidente_mol_m2_dia, esp,etr_etm=etr_etm, theta_sobre_theta_cr=theta_sobre_theta_cr,lai_atual=lai_atual)
    ta_rue = min(ta_rue, esp.ta_max_cm_dia)

    return peso_gdd * ta_gdd + peso_rue * ta_rue

def main_predict_growth(dados_diarios: list[dict], especie_key: str,
                         gdd_inicial: float = 0.0,
                         peso_gdd: float = 0.4, peso_rue: float = 0.6) -> tuple[float, np.ndarray]:
    if especie_key not in ESPECIES:
        raise ValueError(f"Espécie '{especie_key}' não encontrada. Opções: {list(ESPECIES)}")
    esp = ESPECIES[especie_key]
    if not dados_diarios:
        return 0.0, np.array([])

    gdd_acumulado = max(0.0, gdd_inicial)
    serie: list[float] = []

    for i, dia in enumerate(dados_diarios):
        tmax = float(dia["tmax_c"])
        tmin = float(dia["tmin_c"])
        if tmin > tmax:
            warnings.warn(f"Dia {i}: tmin ({tmin}) > tmax ({tmax}) -- valores trocados.")
            tmax, tmin = tmin, tmax
        t_med = (tmax + tmin) / 2.0

        if not (esp.tb <= t_med <= esp.tmax):
            warnings.warn(
                f"Dia {i} ({esp.nome_popular}): T média {t_med:.1f}°C fora da faixa "
                f"calibrada [{esp.tb}, {esp.tmax}]°C -- fator térmico tratado como 0 "
                "para este dia (sem extrapolação além da faixa validada)."
            )

        par = float(dia.get("par_mol_m2_dia", 0.0))
        etr_etm = dia.get("etr_etm")
        theta_rel = dia.get("theta_theta_cr")
        if etr_etm is None and theta_rel is None:
            raise ValueError(
                f"Dia {i}: informe 'etr_etm' ou 'theta_theta_cr' "
                f"(esta espécie usa o tipo '{esp.tipo_estresse_hidrico}')."
            )

        gdd_dia = graus_dia_diario(tmax, tmin, esp.tb)
        gdd_acumulado_ontem = gdd_acumulado
        gdd_acumulado = gdd_acumulado_ontem + gdd_dia

        ta_dia = modelo_hibrido(
            gdd_acumulado, gdd_acumulado_ontem, t_med, par, esp,
            etr_etm=etr_etm, theta_sobre_theta_cr=theta_rel,
            lai_atual=dia.get("lai_atual"),
            peso_gdd=peso_gdd, peso_rue=peso_rue,
        )
        ta_dia = max(0.0, ta_dia)
        serie.append(ta_dia)

    serie_arr = np.array(serie)
    taxa_hoje = float(serie_arr[-1]) if len(serie_arr) else 0.0
    return taxa_hoje, serie_arr

def rodar_pipeline(lat: float, lon: float, data_ini: str, data_fim: str,
                    especie_key: str, data_corte: str | None = None,
                    peso_gdd: float = 0.4, peso_rue: float = 0.6) -> pd.DataFrame:
    if especie_key not in ESPECIES:
        raise ValueError(f"Espécie '{especie_key}' não cadastrada. "
                          f"Opções: {list(ESPECIES)}")
    esp = ESPECIES[especie_key]

    if data_corte is None:
        data_corte = data_ini

    print(f"-> Buscando clima (NASA POWER) para lat={lat}, lon={lon} "
          f"[{data_ini} a {data_fim}]...")
    df_clima = buscar_clima(lat, lon, data_ini, data_fim)

    print("-> Buscando solo (SoilGrids)...")
    solo = buscar_solo(lat, lon)
    print(f"   textura: argila={solo['argila_pct']:.1f}% areia={solo['areia_pct']:.1f}% "
          f"silte={solo['silte_pct']:.1f}% | fonte: {solo['fonte']}")

    agua_disp = capacidade_agua_disponivel(solo["argila_pct"], solo["areia_pct"])
    print(f"   água disponível estimada: {agua_disp:.2f} mm/cm de solo")

    corte_ts = pd.to_datetime(data_corte)
    if corte_ts < df_clima.index[0] or corte_ts > df_clima.index[-1]:
        raise ValueError(
            f"data_corte ({data_corte}) precisa estar dentro do período "
            f"buscado ({df_clima.index[0].date()} a {df_clima.index[-1].date()})."
        )

    print(f"-> Calculando disponibilidade hídrica do solo (Tb={esp.tb} C, "
          f"espécie: {esp.nome_cientifico}, tipo hídrico: {esp.tipo_estresse_hidrico})...")
    df_agua = calcular_disponibilidade_hidrica(df_clima, esp, agua_disp)
    df_agua["par_mol_m2_dia"] = converter_par_mol(df_agua["radiacao_mj_m2"])

    print(f"-> Aplicando modelo híbrido GDD+RUE-Beta (peso_gdd={peso_gdd}, "
          f"peso_rue={peso_rue}) a partir do corte/início em {data_corte}...")
    df_periodo = df_agua.loc[df_agua.index >= corte_ts].copy()

    dados_diarios = []
    for _, row in df_periodo.iterrows():
        dia = {
            "tmax_c": row["tmax_c"],
            "tmin_c": row["tmin_c"],
            "par_mol_m2_dia": row["par_mol_m2_dia"],
        }
        if esp.tipo_estresse_hidrico == "etr_etm":
            dia["etr_etm"] = row["etr_etm"]
        else:
            dia["theta_theta_cr"] = row["theta_theta_cr"]
        dados_diarios.append(dia)

    taxa_hoje, serie_crescimento = main_predict_growth(
        dados_diarios, especie_key, gdd_inicial=0.0, peso_gdd=peso_gdd, peso_rue=peso_rue,
    )

    df_periodo["crescimento_diario_cm"] = serie_crescimento
    df_periodo["altura_estimada_cm"] = np.minimum(
        np.cumsum(serie_crescimento), esp.h_max_cm
    )
    df_periodo["altura_min_cm"] = df_periodo["altura_estimada_cm"] * (1 - INCERTEZA_PADRAO_PCT)
    df_periodo["altura_max_cm"] = df_periodo["altura_estimada_cm"] * (1 + INCERTEZA_PADRAO_PCT)
    df_periodo["crescimento_acumulado_cm"] = df_periodo["altura_estimada_cm"]

    df_final = df_agua.copy()
    for col in ["crescimento_diario_cm", "altura_estimada_cm", "altura_min_cm",
                "altura_max_cm", "crescimento_acumulado_cm"]:
        df_final[col] = np.nan
        df_final.loc[df_periodo.index, col] = df_periodo[col]

    df_final.attrs["especie"] = esp
    df_final.attrs["solo"] = solo
    df_final.attrs["localizacao"] = (lat, lon)
    df_final.attrs["data_corte"] = data_corte
    df_final.attrs["pesos_hibrido"] = (peso_gdd, peso_rue)
    return df_final

def resumo_texto(df: pd.DataFrame) -> str:
    esp: EspecieParams = df.attrs["especie"]
    data_corte = df.attrs.get("data_corte", df.index[0].strftime("%Y-%m-%d"))
    peso_gdd, peso_rue = df.attrs.get("pesos_hibrido", (0.4, 0.6))
    df_pos_corte = df[df["altura_estimada_cm"].notna()]
    ultimo = df_pos_corte.iloc[-1]

    dias_desde_corte = len(df_pos_corte)
    crescimento_medio_dia = df_pos_corte["crescimento_diario_cm"].mean()
    dia_maior_crescimento = df_pos_corte["crescimento_diario_cm"].idxmax()
    maior_crescimento = df_pos_corte["crescimento_diario_cm"].max()

    linhas = [
        f"Espécie: {esp.nome_cientifico} ({esp.nome_popular})",
        f"Hábito/aplicação: {esp.habito_aplicacao}",
        f"Referência: {esp.referencia}",
        f"Modelo: híbrido GDD + RUE-Beta (peso_gdd={peso_gdd}, peso_rue={peso_rue})",
        f"Data do corte / início da medição: {data_corte}",
        f"Altura estimada final: {ultimo['altura_estimada_cm']:.1f} cm "
        f"(faixa {ultimo['altura_min_cm']:.1f}-{ultimo['altura_max_cm']:.1f} cm, "
        f"incerteza genérica ±{INCERTEZA_PADRAO_PCT*100:.0f}% -- não calibrada por espécie)",
        f"Altura máxima típica da espécie: {esp.h_max_cm:.1f} cm",
        f"Crescimento total desde o corte: {ultimo['crescimento_acumulado_cm']:.1f} cm",
        f"Crescimento médio: {crescimento_medio_dia:.2f} cm/dia",
        f"Maior crescimento em um único dia: {maior_crescimento:.2f} cm "
        f"(em {dia_maior_crescimento.date()})",
        "",
        "AVISO: parâmetros de literatura (pesquisa.pdf), sem calibração de campo local.",
    ]
    return "\n".join(linhas)

def plotar(df: pd.DataFrame, caminho_png: str) -> None:
    import matplotlib.pyplot as plt

    esp: EspecieParams = df.attrs["especie"]
    data_corte = df.attrs.get("data_corte", df.index[0].strftime("%Y-%m-%d"))

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

    ax1.plot(df.index, df["altura_estimada_cm"], label="Altura estimada", color="green")
    ax1.fill_between(df.index, df["altura_min_cm"], df["altura_max_cm"],
                      color="green", alpha=0.2, label="Faixa de incerteza")
    ax1.axvline(pd.to_datetime(data_corte), color="brown", linestyle="--",
                label="Corte / início da medição")
    ax1.set_title(f"Altura estimada -- {esp.nome_popular} ({esp.nome_cientifico})")
    ax1.set_ylabel("Altura (cm)")
    ax1.legend()

    ax2.bar(df.index, df["crescimento_diario_cm"], color="seagreen", width=0.9,
            label="Crescimento diário (modelo híbrido)")
    ax2.axhline(0, color="black", linewidth=0.6)
    ax2.set_title("Progressão de crescimento (cm/dia)")
    ax2.set_xlabel("Data")
    ax2.set_ylabel("Crescimento (cm/dia)")
    ax2.legend()

    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(caminho_png, dpi=150)
    print(f"-> Gráfico salvo em: {caminho_png}")
    # plt.show()  <-- Comentado para não travar o servidor FastAPI

def main():
    parser = argparse.ArgumentParser(
        description="Prevê altura de 10 espécies de gramíneas a partir de clima+solo "
                    "(NASA POWER + SoilGrids) usando o modelo híbrido GDD + RUE-Beta."
    )
    parser.add_argument("--lat", type=float, required=True, help="Latitude (graus decimais)")
    parser.add_argument("--lon", type=float, required=True, help="Longitude (graus decimais)")
    parser.add_argument("--inicio", type=str, required=True, help="Data inicial YYYY-MM-DD")
    parser.add_argument("--fim", type=str, required=True, help="Data final YYYY-MM-DD")
    parser.add_argument("--especie", type=str, default="bermuda",
                         choices=list(ESPECIES), help="Espécie de grama alvo")
    parser.add_argument("--data_corte", type=str, default=None,
                         help="Data do corte/início da medição de altura (YYYY-MM-DD). "
                              "Se omitida, usa --inicio como referência.")
    parser.add_argument("--peso_gdd", type=float, default=0.4,
                         help="Peso do submodelo GDD (tendência) na média ponderada híbrida.")
    parser.add_argument("--peso_rue", type=float, default=0.6,
                         help="Peso do submodelo RUE-Beta (ajuste fino) na média ponderada híbrida.")
    parser.add_argument("--csv", type=str, default="previsao_altura.csv",
                         help="Caminho do CSV de saída")
    parser.add_argument("--png", type=str, default="previsao_altura.png",
                         help="Caminho do gráfico de saída")
    args = parser.parse_args()

    df = rodar_pipeline(args.lat, args.lon, args.inicio, args.fim, args.especie,
                         data_corte=args.data_corte, peso_gdd=args.peso_gdd, peso_rue=args.peso_rue)

    df_saida = df[[
        "tmax_c", "tmin_c", "precip_mm", "eto_mm", "fator_agua_solo",
        "par_mol_m2_dia", "altura_estimada_cm", "altura_min_cm", "altura_max_cm",
        "crescimento_diario_cm", "crescimento_acumulado_cm",
    ]]
    df_saida.to_csv(args.csv, index_label="data")
    print(f"-> Série temporal salva em: {args.csv}")

    plotar(df, args.png)

    print("\nResumo")
    print(resumo_texto(df))

# O bloco de execução global abaixo foi removido para evitar travamentos durante a importação pela API